apiVersion: v1
kind: Template
metadata:
  name: genexus
  annotations:
    openshift.io/display-name: Genexus
    iconClass: fa fa-code
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    triggers:
    - type: "ConfigChange"
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${IMAGE_NAME}:${IMAGE_VERSION}
          namespace: openshift
      type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - name: ${APP_NAME}
          image: ${APP_NAME}:latest
          env: {}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: 1024Mi
            requests:
              memory: 1024Mi
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: genexus
- description: Git Repository
  displayName: Git Repository
  name: GIT_REPO
  required: true
  value: ssh://git@github.com:juanchiriera/openshift-binary-deploy-pipeline.git
- description: Git Branch
  displayName: Git Branch
  name: GIT_BRANCH
  required: true
  value: master
- name: ENVIRONMENT
  displayName: Environment
  description: Environment
  required: true
  value: salud
- name: IMAGE_NAME
  displayName: Image Base Name
  description: Image Base Name
  required: true
  value: jboss-webserver31-tomcat8-openshift
- name: IMAGE_VERSION
  displayName: Image Base Version
  description: Image Base Version
  required: true
  value:  latest
- name: USER
  displayName: DB User
  required: true
  value: sisauser
- name: PASSWORD
  displayName: DB Password
  required: true
  value: o0O1lLI134ewdfa5f
