runCIPipeline(application: env.APP_NAME,
              devProject: "genexus-dev",
              agent: "nodejs",
              compileCommands: "curl -u admin:admin123 --create-dirs -o ./openshift/wars/genexus.war http://nexus-jenkins.apps.shared.na.openshift.opentlc.com/nexus/service/local/repositories/releases/content/test_group/test_artifact/1.0/test_artifact-1.0.war",
              testCommands: "",
              artifactsDir: "./openshift",
              applicationTemplate: "./openshift/template.yaml")
